CREATE TABLE IF NOT EXISTS "assets" (
"﻿id" INT NULL,
"name" TEXT NULL,
"type" TEXT NULL,
"serial" TEXT NULL,
"location" TEXT NULL,
"condition" TEXT NULL
);

INSERT INTO assets VALUES
(1,'Acer TravelMate P258-M','Laptop','NXVC7EK0016110ECD87600','WithIT','Working'),
(2,'iPad Air 2','iPad','DMPRG3REG5VW','mhulland','working\, with case'),
(3,'Apple TV 4th Generation','Apple TV','C07PXJRKG9RM','WithIT','Working with Cables'),
(4,'Oculus Go','VR Headset','1KWPH8037V8152','WithIT','Workgin\, in box'),
(5,'Oculus Go Headset-01','VR Headset','1KWPH8037V8152','WithIT','In Box\, All Cables'),
(6,'Oculus Go Headset-02','VR Headset','1KWPH800VL8203','WithIT','In Box\, All Cables'),
(7,'Oculus Go Headset-03','VR Headset','1KWPH800FG8203','WithIT','In Box\, All Cables'),
(8,'Oculus Go Headset-04','VR Headset','1KWPH802AR8203','WithIT','In Box\, All Cables'),
(9,'Oculus Go Headset-05','VR Headset','1KWPH8037S8195','WithIT','In Box\, All Cables'),
(10,'iPad Air 2 (Wi-Fi)','iPad','DMPRG3REG5VW','Matthew Hulland','Working'),
(11,'iPad Air 2 (Wi-Fi)','iPad','DMPRM7S3G5VW','Selina Couttignane','Working'),
(12,'iPad Air 2 (Wi-Fi)','iPad','DMPRPZGVG5VW','withIT','Working'),
(13,'iPad Air 2 (Wi-Fi)','iPad','DMPRQ5YTG5VW','Levi Meek-Carter','Working'),
(14,'iPad Air 2 (Wi-Fi)','iPad','DMPRQ8D8G5VW','Jael Gomez-Santana','Working'),
(15,'iPad Air 2 (Wi-Fi)','iPad','DMPRQ8K9G5VW','Helene Smit','Working'),
(16,'iPad Air 2 (Wi-Fi)','iPad','DMPRTYHKG5VW','Carles Rubio Arias','Working'),
(17,'iPad Air 2 (Wi-Fi)','iPad','DMPS8958G5W1','Chris Daly','Working'),
(18,'iPad Air 2 (Wi-Fi)','iPad','DMPS8EM6G5W1','Xiaojing McFadden','Working'),
(19,'iPad Air 2 (Wi-Fi)','iPad','DMPS8ENAG5W1','Michelle Anderson','Working'),
(20,'iPad Air 2 (Wi-Fi)','iPad','DMPS8ER1G5W1','Claire Robinson','Working'),
(21,'iPad Air 2 (Wi-Fi)','iPad','DMPS8FA8G5W1','Sabina Hussain','Working'),
(22,'iPad Air 2 (Wi-Fi)','iPad','DMPS8FAVG5W1','Gill Waller        ','Working'),
(23,'iPad Air 2 (Wi-Fi)','iPad','DMPS8FCDG5W1','Ben Godber','Working'),
(24,'iPad Air 2 (Wi-Fi)','iPad','DMPS8FGRG5W1','Nina Kyprianidis','Working'),
(25,'iPad Air 2 (Wi-Fi)','iPad','DMPS8FWPG5W1','Andrew Campbell','Working'),
(26,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','DMPYXFMKJF8J','Stewart Young','Working'),
(27,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','DMPYXGNQJF8J','Laura Briggs','Working'),
(28,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','DMPYXMRBJF8J','Sarah Parnaby','Working'),
(29,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','DMPYXMYWJF8J','Caroline Gregson','Working'),
(30,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','DMPYXPJWJF8J','Ellen Surtees','Working'),
(31,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','DMPZ3C1TJF8J','Laura Brooks','Working'),
(32,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','DMPZ56P2JF8J','Laura Campbell','Working'),
(33,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','DMPZ58ATJF8J','Florence Keith','Working'),
(34,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','DMPZ58DJJF8J','Gabby Myers','Working'),
(35,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','DMPZ58FBJF8J','Amy Wilton','Working'),
(36,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','DMPZ58YFJF8J','Chris Jones','Working'),
(37,'iPad Air 2 (Wi-Fi)','iPad','DMQRF3VZG5VW','Kate Gibson','Working'),
(38,'iPad Air 2 (Wi-Fi)','iPad','DMQRKNZYG5VW','Keely Oakes','Working'),
(39,'iPad Air 2 (Wi-Fi)','iPad','DMQRP2H8G5VW','Sarah Goodsell','Working'),
(40,'iPad Air 2 (Wi-Fi)','iPad','DMQRPCMTG5VW','Rhianwen Bedford','Working'),
(41,'iPad Mini','iPad','F9FSHY2SFCM6','Julie Barron','Working'),
(42,'iPad 5th Generation (Wi-Fi)','iPad','F9FTGFXNHLF9','George Peters','Working'),
(43,'iPad 5th Generation (Wi-Fi)','iPad','F9FTHYRXHLF9','Jack Pickett','Working'),
(44,'iPad 5th Generation (Wi-Fi)','iPad','F9FTJ67WHLF9','Lauren Swain','Working'),
(45,'iPad 5th Generation (Wi-Fi)','iPad','F9FTJN5XHLF9','Matthew Garwell','Working'),
(46,'iPad 5th Generation (Wi-Fi)','iPad','F9FTJNP4HLF9','Steven Duff','Working'),
(47,'iPad 5th Generation (Wi-Fi)','iPad','F9FTJSP4HLF9','Frankie Hodgson','Working'),
(48,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','F9FX11VCJF8J','Michelle Grant','Working'),
(49,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','F9FX2LMLJF8J','Aisling Hurley','Working'),
(50,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','F9FX2WTUJF8J','Charlotte Tigwell','Working'),
(51,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','F9FYGN56JF8J','Wendy Whearity','Working'),
(52,'iPad 5th Generation (Wi-Fi)','iPad','F9GTJ2AVHLF9','Bee Tregoning','Working'),
(53,'iPad 5th Generation (Wi-Fi)','iPad','F9GTJ2MKHLF9','Janine Bloomfield','Working'),
(54,'iPad 5th Generation (Wi-Fi)','iPad','F9GTJ3HVHLF9','Kate Pass','Working'),
(55,'iPad 5th Generation (Wi-Fi)','iPad','F9GTJ3RAHLF9','Thomas Bartlett','Working'),
(56,'iPad 5th Generation (Wi-Fi)','iPad','GCGV81TEHLF9','Lizzie Islip','Working'),
(57,'iPad 5th Generation (Wi-Fi)','iPad','GCGV85JQHLF9','Sebastian Lair','Working'),
(58,'iPad 5th Generation (Wi-Fi)','iPad','GCGV86F8HLF9','Sophie Reynolds','Working'),
(59,'iPad 5th Generation (Wi-Fi)','iPad','GCGV87QXHLF9','Hazel Johnston','Working'),
(60,'iPad 5th Generation (Wi-Fi)','iPad','GCGV890HHLF9','Stefan Apter','Working'),
(61,'iPad 5th Generation (Wi-Fi)','iPad','GCGV89J2HLF9','Louise Scarr','Working'),
(62,'iPad 5th Generation (Wi-Fi)','iPad','GCGV8RTTHLF9','Katy Dziedzic','Working'),
(63,'iPad 5th Generation (Wi-Fi)','iPad','GCGV8S3JHLF9','Natalia Seweryn','Working'),
(64,'iPad 5th Generation (Wi-Fi)','iPad','GCHV6M5SHLF9','Samir Kharbouch','Working'),
(65,'iPad 5th Generation (Wi-Fi)','iPad','GCHV6MHBHLF9','Melissa Corby','Working'),
(66,'iPad 5th Generation (Wi-Fi)','iPad','GCHV6MJ2HLF9','Lucy Davis','Working'),
(67,'iPad 5th Generation (Wi-Fi)','iPad','GCHV6MLWHLF9','Alex Murray-Smith','Working'),
(68,'iPad 5th Generation (Wi-Fi)','iPad','GCHV6N54HLF9','Alice Mitchell','Working'),
(69,'iPad 5th Generation (Wi-Fi)','iPad','GCHV6P0QHLF9','Sydney Bautista','Working'),
(70,'iPad 5th Generation (Wi-Fi)','iPad','GCHV6R5DHLF9','Noura Gomaa','Working'),
(71,'iPad 5th Generation (Wi-Fi)','iPad','GCHV6R68HLF9','Indrani Bhattacharya','Working'),
(72,'iPad 5th Generation (Wi-Fi)','iPad','GCHV6RFUHLF9','Amy Ellis','Working'),
(73,'iPad 5th Generation (Wi-Fi)','iPad','GCHV6RK5HLF9','Katherine Smith','Working'),
(74,'iPad 5th Generation (Wi-Fi)','iPad','GCHV6S8CHLF9','Sam London','Working'),
(75,'iPad 5th Generation (Wi-Fi)','iPad','GCHV6SBDHLF9','Jessica Whitfield','Working'),
(76,'iPad 5th Generation (Wi-Fi)','iPad','GCHV6VGGHLF9','Tim Jefferson','Working'),
(77,'iPad 5th Generation (Wi-Fi)','iPad','GCHV6WW1HLF9','Helene Smit','Working'),
(78,'iPad 5th Generation (Wi-Fi)','iPad','GCHV6WYCHLF9','Daniel Morgan','Working'),
(79,'iPad 5th Generation (Wi-Fi)','iPad','GCHV6XUJHLF9','Rebecca Bishop','Working'),
(80,'iPad 5th Generation (Wi-Fi)','iPad','GCHV81YUHLF9','Camilla Ford','Working'),
(81,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','GG7XQN3UJF8J','Hannah Maciw','Working'),
(82,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','GG7XQX2SJF8J','Sandra Allwright','Working'),
(83,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','GG8XQ48YJF8J','Catherine Gregson','Working'),
(84,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','GG8XQ62XJF8J','Charity Ellis','Working'),
(85,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','GG8XQ66KJF8J','Ines Arsenio','Working'),
(86,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','GG8XQ6LBJF8J','Helene Smit','Working'),
(87,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','GG8XQCQ8JF8J','Oliver Read','Working'),
(88,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','GG8XQPGAJF8J','Maria Del Carmen','Working'),
(89,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','GG8XQX9EJF8J','Jun Yan','Working'),
(90,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','GQ8XQ16DJF8J','Julie Barron','Working'),
(91,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','GQ8XQ4QAJF8J','Victoria Millar','Working'),
(92,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','GQ8XQ4R1JF8J','Jenny Beer','Working'),
(93,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','GQ8XQAADJF8J','Wendy Meads','Working'),
(94,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','GQ8XQDCFJF8J','Maria Mendiguren ','Working'),
(95,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','GQ8XQV30JF8J','Justin Watson','Working'),
(96,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','F9GCPH6FM3M','Caroline Fletcher','Working'),
(97,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','F9GCPHLCMF3M','Jules Darker Larkin','Working'),
(98,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','F9GCPH0AMF3M','Euan Andrews','Working'),
(99,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','F9GCP88KMF3M','Sophia Martinez','Working'),
(100,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','F9GCPPW1MF3M','Claire Burke','Working'),
(101,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','F9GCPLH3MF3M','Natasha Sharma','Working'),
(102,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','F9GCPGUWMF3M','Clare Hunton Moore','Working'),
(103,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','F9GCPPE3MF3M','Connor Lewis','Working'),
(104,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','F9GCP1DTMF3M','Amy Major','Working'),
(105,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','F9GCPLFUMF3M','Amy Tucker','Working'),
(106,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','F9GCPGQZMF3M','Lea Kidd','Working'),
(107,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','F9GCPQ1GMF3M','Nicole Ward','Working'),
(108,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','F9GCPPZ7MF3M','Craig Tedridge','Working'),
(109,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','F9GCPGELMF3M','Kenny Chan','Working'),
(110,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','F9GCPHGWMF3M','Wendy Whearity','Working'),
(111,'iPad 9.7\" 6th Gen (Wi-Fi Only)','iPad','DMPCW5G9MF3M','Charlie Gamage','Working'),
(112,'ACER ','Laptop','NXVC7EK0016110ECD87600','WithIT','Working\, With Charger'),
(113,'ACER A1','Laptop','NXVC7EK0016110EC5E7600','WithIT','Working\, With Charger'),
(114,'ACER A3','Laptop','NXVC7EK0016110EC977600','WithIT','Working\, With Charger'),
(115,'DELL','Laptop','7CSKLC2','WithIT','Working\, With Charger'),
(116,'DELL','Laptop','1LL2762','WithIT','Working\, With Charger'),
(117,'DELL','Laptop','DT78362','WithIT','Working\, With Charger'),
(118,'DELL','Laptop','BJ8M562','WithIT','Working\, With Charger'),
(119,'DELL','Laptop','CXX4Y52','WithIT','Working\, With Charger'),
(120,'DELL','Laptop','751Q362','WithIT','Working\, With Charger'),
(121,'DELL','Laptop','3HK4Y52','WithIT','Working\, With Charger'),
(122,'DELL','Laptop','6ZXW162','WithIT','Working\, With Charger'),
(123,'DELL','Laptop','JGMS162','WithIT','Working\, With Charger'),
(124,'DELL','Laptop','1LK4Y52','WithIT','Working\, With Charger'),
(125,'DELL','Laptop','7w0zc72','WithIT','Working\, With Charger'),
(126,'DELL','Laptop','45r4y52','WithIT','Working\, With Charger'),
(127,'DELL','Laptop','1q78362','WithIT','Working\, With Charger'),
(128,'DELL','Laptop','4rk4y52','WithIT','Working\, With Charger'),
(129,'DELL','Laptop','2ns8362','WithIT','Working\, With Charger'),
(130,'DELL','Laptop','70d4y52','WithIT','Working\, With Charger'),
(131,'DELL','Laptop','cvjw662','WithIT','Working\, With Charger'),
(132,'DELL','Laptop','3csw662','WithIT','Working\, With Charger'),
(133,'DELL','Laptop','c7ct162','WithIT','Working\, With Charger'),
(134,'DELL','Laptop','g01zc72','WithIT','Working\, With Charger'),
(135,'DELL','Laptop','973zc72','WithIT','Working\, With Charger'),
(136,'DELL','Laptop','ctlp662','WithIT','Working\, With Charger'),
(137,'DELL','Laptop','dvlp662','WithIT','Working\, With Charger'),
(138,'DELL','Laptop','9h78362','WithIT','Working\, With Charger'),
(139,'DELL','Laptop','7YMW662','WithIT','Working\, With Charger'),
(140,'DELL// WIN-8375TMEE5MH','Laptop','6X0ZC72','WithIT','Working\, With Charger'),
(141,'HP','Laptop','5cd9125sr1','WithIT','Working\, With Charger'),
(142,'HP','Laptop','5cd9125sr6','WithIT','Working\, With Charger'),
(143,'HP','Laptop','5cd9125srk','WithIT','Working\, With Charger'),
(144,'WOK-DELL-01','Laptop','CQVJGC2','Mark Anderson','Working\, With Charger'),
(145,'WOK-DELL-02','Laptop','CV0TS32','Matthew Garwell','Working\, With Charger'),
(146,'WOK-DELL-03','Laptop','CS6WG72','WithIT','Working\, With Charger'),
(147,'WOK-DELL-05','Laptop','G4Y4Y52','Keely Oakes','Working\, With Charger'),
(148,'WOK-DELL-06','Laptop','DZLP662','SEN','Working\, With Charger'),
(149,'WOK-DELL-08','Laptop','88R4Y52','Frankie Hodgson','Working\, With Charger'),
(150,'WOK-DELL-09','Laptop','8QBXG72','R Bedford','Working\, With Charger'),
(151,'WOK-DELL-10','Laptop','50LW662','Sara Harwood','Working\, With Charger'),
(152,'WOK-DELL-11','Laptop','jz9zc72','WithIT','Working\, With Charger'),
(153,'WOK-DELL-12','Laptop','jl78362','Xiaojing Chen','Working\, With Charger'),
(154,'WOK-DELL-13','Laptop','3MK4Y52','WithIT','Working\, With Charger'),
(155,'WOK-DELL-15','Laptop','DZJW662','Liz Tuhy','Working\, With Charger'),
(156,'WOK-DELL-16','Laptop','2gk4y52','Emma Bartle','Working\, With Charger'),
(157,'WOK-DELL-17','Laptop','BCSW662','Kate Pass','Working\, With Charger'),
(158,'WOK-DELL-18','Laptop','6VLC662','Hazel Johnston/Seb Lair','Working\, With Charger'),
(159,'WOK-DELL-19','Laptop','JGK4Y52','Steven Duff','Working\, With Charger'),
(160,'WOK-DELL-20','Laptop','5LK4Y52','Imke Wilson','Working\, With Charger'),
(161,'WOK-DELL-21','Laptop','jb3zc72','WithIT','Working\, With Charger'),
(162,'WOK-DELL-22','Laptop','DWMW662','WithIT','Working\, With Charger'),
(163,'WOK-DELL-23','Laptop','GPYVS32','C Ford','Working\, With Charger'),
(164,'WOK-DELL-24','Laptop','6BL2762','WithIT','Working\, With Charger'),
(165,'WOK-DELL-IT02','Laptop','7V7YG72','Mac Hooper','Working\, With Charger'),
(166,'WOK-HP-01','Laptop','5cd9125sqs','WithIT','Working\, With Charger'),
(167,'Apple TV 01 - (4th Generation)','Apple TV','C07PXJRKG9RM','WithIT','Working\, With All Cables'),
(168,'Apple TV 02 - (4th Generation)','Apple TV','C07PXJLDG9RM','WithIT','Working\, With All Cables'),
(169,'Apple TV 03 - (4th Generation)','Apple TV','C07PXJU5G9RM','WithIT','Working\, With All Cables'),
(170,'Apple TV 04 - (4th Generation)','Apple TV','C1MPWLF6G9RM','WithIT','Working\, With All Cables'),
(171,'Apple TV 05 - (4th Generation)','Apple TV','DY5PXYJQG9RM','WithIT','Working\, With All Cables'),
(172,'Apple TV 06 - (4th Generation)','Apple TV','C1MPWMC6G9RM','WithIT','Working\, With All Cables'),
(173,'Apple TV 07 - (4th Generation)','Apple TV','C0HQ1O12G9RM','WithIT','Working\, With All Cables'),
(174,'Apple TV 08 - (4th Generation)','Apple TV','C0HQ1AUVG9RM','WithIT','Working\, With All Cables'),
(175,'Apple TV 09 - (4th Generation)','Apple TV','DY3Q1CUUG9RM','WithIT','Working\, With All Cables'),
(176,'Apple TV 10 - (4th Generation)','Apple TV','C0HQ19N4G9RM','WithIT','Working\, With All Cables'),
(177,'HP EliteDesk','Desktop','WOK-F2','F2','Working\, Video no Sound'),
(178,'Novatech','Desktop','WOK-F4','F4','Working\, Video and Sound'),
(179,'HP EliteDesk','Desktop','WOK-F5','F5','Working\, Video and Sound'),
(180,'Fujitsu Esprimo','Desktop','WOK-FOOD-01','FT1','Working\, Video and Sound'),
(181,'Fujitsu Esprimo','Desktop','WOK-SC4','SC4','Working\, Video and Sound'),
(182,'Novatech','Desktop','WOK-SC5','SC5','Working\, Video and Sound'),
(183,'HP EliteDesk','Desktop','WOK-FOOD-02','FT2','Working\, Video and Sound'),
(184,'HP EliteDesk','Desktop','WOK-SC6','SC6','No Video\, Sound or Network'),
(185,'Novatech','Desktop','WOK-SC9','SC9','Working\, Video and Sound'),
(186,'HP EliteDesk','Desktop','WOK-SC7','SC7','Working\, Video and Sound'),
(187,'Fujitsu Esprimo','Desktop','WOK-SC8','SC8','Working\, Video and Sound'),
(188,'Novatech','Desktop','WOK-IT5','IT5','Working\, Video no Sound'),
(189,'Novatech','Desktop','WOK-F21','F21','Working\, Video no Sound'),
(190,'Fujitsu Esprimo','Desktop','WOK-20','F20','Working\, Video and Sound'),
(191,'Fujitsu Esprimo','Desktop','WOK-F19','F19','Working\, Video and Sound'),
(192,'Fujitsu Esprimo','Desktop','WOK-F6','F6','Working\, Video and Sound'),
(193,'Fujitsu Esprimo','Desktop','WOK-F7','F7','Working\, Video and Sound'),
(194,'Fujitsu Esprimo','Desktop','WOK-17','F17','Working\, Video no Sound'),
(195,'Fujitsu Esprimo','Desktop','WOK-F8','F8','Working\, Video and Sound'),
(196,'Fujitsu Esprimo','Desktop','WOK-F16','F16','Working\, Video and Sound'),
(197,'HP EliteDesk','Desktop','WOK-F9','F9','Doesn''t Boot'),
(198,'HP EliteDesk','Desktop','WOK-F10','F10','Working\, Video and Sound'),
(199,'Fujitsu Esprimo','Desktop','WOK-F15','F15','Working\, Video and Sound'),
(200,'Fujitsu Esprimo','Desktop','WOK-F14','F14','Working\, Video and Sound'),
(201,'HP EliteDesk','Desktop','WOK-F11','F11','Doesn’t Boot'),
(202,'HP EliteDesk','Desktop','WOK-F12','F12','Working\, Sound no Video'),
(203,'HP EliteDesk','Desktop','WOK-G8','G8','Working\, Video and Sound'),
(204,'HP EliteDesk','Desktop','WOK-G9','G9','Working\, Video and Sound'),
(205,'HP EliteDesk','Desktop','WOK-G9','G9','Working\, Video and Sound'),
(206,'HP EliteDesk','Desktop','WOK-G10','G10','Working\, Video and Sound'),
(207,'Novatech','Desktop','WOK-G5','G5','Working\, Video no Sound'),
(208,'Novatech','Desktop','WOK-G11','G11','Working\, Video and Sound'),
(209,'Novatech','Desktop','WOK-G12','G12','Working\, Video and Sound'),
(210,'Fujitsu Esprimo','Desktop','WOK-G4','G4','Working\, Video and Sound'),
(211,'Novatech','Desktop','WOK-G3','G3','Working\, Video and Sound'),
(212,'Fujitsu Esprimo','Desktop','WOK-G13','G13','Working\, Video and Sound'),
(213,'Fujitsu Esprimo','Desktop','WOK-G14','G14','Working\, Video and Sound'),
(214,'Fujitsu Esprimo','Desktop','WOK-G2','G2','Working\, Video and Sound'),
(215,'Fujitsu Esprimo','Desktop','WOK-G15','G15','Working\, Video and Sound'),
(216,'Novatech','Desktop','WOK-G16','G16','Working\, Video and Sound'),
(217,'Fujitsu Esprimo','Desktop','WOK-ITG','IT1','Working\, Video and Sound'),
(218,'iMac','Desktop','WOK-Mu1','Mu1','Working\, Video and Sound'),
(219,'Fujitsu Esprimo','Desktop','WOK-SC1','SC10','Working\, Video and Sound'),
(220,'Fujitsu Esprimo','Desktop','WOK-Mu1','Mu1','Working\, Video no Sound'),
(221,'Fujitsu Esprimo','Desktop','WOK-Sc2','Sc2','Working\, Video and Sound'),
(222,'Fujitsu Esprimo','Desktop','WOK-Sc3','Sc3','Working\, Video and Sound'),
(223,'Fujitsu Esprimo','Desktop','WOK-St1','St1','Working\, Video and Sound'),
(224,'Fujitsu Esprimo','Desktop','WOK-ST3','ST3','Working\, Video no Sound'),
(225,'Fujitsu Esprimo','Desktop','WOK-ST2','ST2','Working\, Video and Sound');